// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaVhC8wcwrPCTKsHDLt2chnVU98ohGLJM',
    appId: '1:360756867997:web:fb519fdf0cc7a24fac7574',
    messagingSenderId: '360756867997',
    projectId: 'news-app-21371',
    authDomain: 'news-app-21371.firebaseapp.com',
    storageBucket: 'news-app-21371.appspot.com',
    measurementId: 'G-K3SQY0QKNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJCxhBd4m0Dfucm4dsz6SAGZARXcdIXtI',
    appId: '1:360756867997:android:2fa22172d11260cdac7574',
    messagingSenderId: '360756867997',
    projectId: 'news-app-21371',
    storageBucket: 'news-app-21371.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkuLaUSzQ2SfPs9MM5hjngh4mPxg0-DQo',
    appId: '1:360756867997:ios:c6876279b1044860ac7574',
    messagingSenderId: '360756867997',
    projectId: 'news-app-21371',
    storageBucket: 'news-app-21371.appspot.com',
    iosClientId: '360756867997-389u0ufv034ntd2sing18gdifbqf4icu.apps.googleusercontent.com',
    iosBundleId: 'innopolis.university.newsApp',
  );
}
